# Set update schedule for GitHub Actions to check they are up to date
# If one of the github actions is out of date, dependabot will open a
# PR to update the version of that action

version: 2
updates:
  # Maintain the requirements in the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - JoranAngevaare
  # Maintain the requirements requirements folder
  - package-ecosystem: "pip"
    directory: "/extra_requirements"
    ignore: autodocsumm commonmark gitpython graphviz nbsphinx numpy recommonmark scipy spinx typing-extensions
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    assignees:
      - JoranAngevaare
