# Test package every time

name: Build

# Controls when the action will run.

# Trigger this code when a new release is published
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # NB: For python3.6 we are going to explicitly test without a database
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install python dependencies
        uses: py-actions/py-dependency-install@v2
      - name: Install peak_matching
        run: bash .github/scripts/install_pema.sh
      - name: Install pytest and hypothesis
        run: pip install pytest hypothesis flake8 pytest-cov boltons
      - name: patch utilix file
        # Since we skip this step for python 3.7, we are testing without the database
        if: matrix.python-version == 3.7 ||  matrix.python-version == 3.8
        run: bash .github/scripts/create_readonly_utilix_config.sh
        env:
          RUNDB_API_URL: ${{ secrets.RUNDB_API_URL }}
          RUNDB_API_USER_READONLY: ${{ secrets.RUNDB_API_USER_READONLY }}
          RUNDB_API_PASSWORD_READONLY: ${{ secrets.RUNDB_API_PASSWORD_READONLY}}
          PYMONGO_URL: ${{ secrets.PYMONGO_URL }}
          PYMONGO_USER: ${{ secrets.PYMONGO_USER }}
          PYMONGO_PASSWORD: ${{ secrets.PYMONGO_PASSWORD }}
          PYMONGO_DATABASE: ${{ secrets.PYMONGO_DATABASE }}
      - name: Test package
        run: |
          pytest -v --durations 0
      - name: goodbye
        run: echo goodbye
