# Test package every time

name: Test package

# Controls when the action will run.

# Trigger this code when a new release is published
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
    branches:
      - main

jobs:
  Run pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install python dependencies
        uses: py-actions/py-dependency-install@v2
      - name: Install peak_matching
        run: bash .github/scripts/install_peak_matching.sh
      - name: Install pytest and hypothesis
        run: pip install pytest hypothesis
      - name: Test package
        run: |
          pytest
      - name: goodbye
        run: echo goodbye
